services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  k6:
    image: grafana/k6
    volumes:
      - ./:/scripts
    # 실행 시킬 js들과 프로메테우스에 결과 전달
    command: run /scripts/user-setup.js -o experimental-prometheus-rw
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=avg,sum,count
    depends_on:
      - prometheus
